---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-recommender-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song-recommender
  template:
    metadata:
      labels:
        app: lucassouza-song-recommender
    spec:
      containers:
      - name: song-recommender
        image: zzzluquinhas/api_container:latest
        ports:
        - containerPort: 32199
        volumeMounts:
         - name: data-volume
            mountPath: /home/lucassouza/project2-pv
        env:
        - name: DATASET
        value: https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds1.csv
      volumes:
      - name: data-volume
      persistentVolumeClaim:
        claimName: project2-pv-lucassouza
